/**
 * CAOS_SEISMIC — 30-day OUTLOOK data client.
 *
 * The 1-7 day product is ETAS (Monitoring). The 30-day outlook is a SEPARATE, longer-horizon surface
 * driven by the geodetic-context neural BACKGROUND — the one place a covariate measurably beats ETAS
 * (E11/E14: the neural wins at 30 d, loses at 1-7 d). It is generated by a weekly neural refit (the
 * background is time-flat, so daily refitting is unnecessary) and published as its own static artifact:
 *   - `<base>/data/outlook-index.json`            — the latest pointer
 *   - `<base>/data/outlook-30d-<date>.json.gz`    — the compact 30-day field
 *   - `<base>/data/outlook-evidence-30d.json`     — the leakage-free per-view IGPE vs ETAS at 30 d
 *
 * This client is read-only and gzip-aware (raw `.gz` blobs are inflated via DecompressionStream),
 * mirroring the daily forecast client. It NEVER invents values: a missing cell is implicit long-term
 * baseline, not "safe".
 */

export interface OutlookCell {
  lat: number;
  lon: number;
  /** Expected number of M>=M* events in the 30-day window for this cell. */
  n30: number;
  /** P(>=1 M>=M* event) = 1 - e^{-n30}. */
  p30: number;
}

export interface OutlookArtifact {
  kind: 'outlook_30d';
  issued_at: string;
  horizon_days: number;
  m_threshold: number;
  model: string;
  mc: number;
  n_total_30d: number;
  n_etas_30d: number;
  n_cells: number;
  field: OutlookCell[];
}

export interface OutlookIndex {
  latest?: {
    file: string;
    issued_at: string;
    horizon_days: number;
    n_total_30d: number;
    n_cells: number;
  };
}

export interface OutlookViewEvidence {
  mean_igpe_vs_etas: number | null;
  windows_positive: string;
  n_eq: number;
  ci_excludes_zero: boolean | null;
  t_ci_low: number | null;
}
export interface OutlookEvidence {
  [view: string]: OutlookViewEvidence | OutlookEvidenceSummary;
  _summary: OutlookEvidenceSummary;
}
export interface OutlookEvidenceSummary {
  global_ci_excludes_zero: boolean;
  high_seis_views_positive: number;
  n_high_seis: number;
  verdict: string;
}

function resolveBase(): string {
  try {
    const env = (import.meta as unknown as { env?: { BASE_URL?: string } }).env;
    if (env?.BASE_URL) return env.BASE_URL;
  } catch {
    /* non-Vite env */
  }
  return '/';
}

function dataUrl(file: string): string {
  return `${resolveBase().replace(/\/+$/, '')}/data/${file.replace(/^\/+/, '')}`;
}

function looksGzipped(b: Uint8Array): boolean {
  return b.length >= 2 && b[0] === 0x1f && b[1] === 0x8b;
}

async function fetchMaybeGz<T>(file: string): Promise<T> {
  const res = await fetch(dataUrl(file), { cache: 'no-cache' });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${file}`);
  const buf = await res.arrayBuffer();
  const head = new Uint8Array(buf.slice(0, 2));
  let text: string;
  if (looksGzipped(head)) {
    const DS = (globalThis as { DecompressionStream?: typeof DecompressionStream }).DecompressionStream;
    if (!DS) throw new Error('This browser cannot decode a .gz artifact (DecompressionStream unavailable).');
    text = await new Response(new Blob([buf]).stream().pipeThrough(new DS('gzip'))).text();
  } else {
    text = new TextDecoder('utf-8').decode(buf);
  }
  return JSON.parse(text) as T;
}

/** Load the latest 30-day outlook field + its validation evidence. Returns null pieces gracefully. */
export async function loadOutlook(): Promise<{ artifact: OutlookArtifact; evidence: OutlookEvidence | null }> {
  const index = await fetchMaybeGz<OutlookIndex>('outlook-index.json');
  const file = index.latest?.file;
  if (!file) throw new Error('outlook-index.json has no `latest` pointer.');
  const artifact = await fetchMaybeGz<OutlookArtifact>(file);
  let evidence: OutlookEvidence | null = null;
  try {
    evidence = await fetchMaybeGz<OutlookEvidence>('outlook-evidence-30d.json');
  } catch {
    evidence = null; // evidence is optional; the field still renders
  }
  return { artifact, evidence };
}
